- hosts: localhost    
  connection: local
  become: true

  pre_tasks:
    # - name: Add specified repository into sources list
    #   when: ansible_distribution == "Debian"
    #   apt_repository:
    #     repo: deb http://deb.debian.org/debian buster-backports main
    #     state: present
    - name: update repos (debian)
      when: ansible_distribution in ["Debian", "Ubuntu"]
      apt:
        update_cache: yes
      changed_when: False
  
  tasks:
    - include: tasks/packages.yml
    - include: tasks/users.yml
    - include: tasks/cron.yml

