- name: Install packages
  when: ansible_distribution in ["Debian", "Ubuntu"]
  apt:
    name: 
       - htop
       - zsh
       - apt-transport-https
       - ca-certificates
       - curl
       - gnupg-agent
       - software-properties-common
       - wget
       - neofetch
       - bridge-utils
       - net-tools

